export const DETAILFORM_SAVE_REQUEST = 'DETAILFORM_SAVE_REQUEST'
export const DETAILFORM_SAVE_SUCCESS = 'DETAILFORM_SAVE_SUCCESS'
export const DETAILFORM_SAVE_FAIL = 'DETAILFORM_SAVE_FAIL'

export const FORM_SAVE_REQUEST = 'FORM_SAVE_REQUEST'
export const FORM_SAVE_SUCCESS = 'FORM_SAVE_SUCCESS'
export const FORM_SAVE_FAIL = 'FORM_SAVE_FAIL'

export const EMPLOYEMENTFORM_SAVE_REQUEST = 'EMPLOYEMENTFORM_SAVE_REQUEST'
export const EMPLOYEMENTFORM_SAVE_SUCCESS = 'EMPLOYEMENTFORM_SAVE_SUCCESS'
export const EMPLOYEMENTFORM_SAVE_FAIL = 'EMPLOYEMENTFORM_SAVE_FAIL'


export const QUALIFICATIONFORM_SAVE_REQUEST = 'QUALIFICATIONFORM_SAVE_REQUEST'
export const QUALIFICATIONFORM_SAVE_SUCCESS = 'QUALIFICATIONFORM_SAVE_SUCCESS'
export const QUALIFICATIONFORM_SAVE_FAIL = 'QUALIFICATIONFORM_SAVE_FAIL'

export const OPPURTUNITIESFORM_SAVE_REQUEST = 'OPPURTUNITIESFORM_SAVE_REQUEST'
export const OPPURTUNITIESFORM_SAVE_SUCCESS = 'OPPURTUNITIESFORM_SAVE_SUCCESS'
export const OPPURTUNITIESFORM_SAVE_FAIL = 'OPPURTUNITIESFORM_SAVE_FAIL'

export const DECLARATIONFORM_SAVE_REQUEST = 'DECLARATIONFORM_SAVE_REQUEST'
export const DECLARATIONFORM_SAVE_SUCCESS = 'DECLARATIONFORM_SAVE_SUCCESS'
export const DECLARATIONFORM_SAVE_FAIL = 'DECLARATIONFORM_SAVE_FAIL'

export const PROOF_SAVE_REQUEST = 'PROOF_SAVE_REQUEST'
export const PROOF_SAVE_SUCCESS = 'PROOF_SAVE_SUCCESS'
export const PROOF_SAVE_FAIL = 'PROOF_SAVE_FAIL'

